graph TD
    C/C++ -->|LibClang| ClangAST
    Python["Python"] --> PythonAST[Parso AST] --> UAST
    
    ClangAST -->|转换| UAST

    subgraph `PyBirdViewCode Package Functionalities`

        UAST["统一抽象语法树（UAST）"]
        CommonUtils["Clang 常用方法接口"]
        
        UAST -->|Control Flow Building| CFG["控制流图（CFG）"]
        CFG --> ControlFlowAnalysis["控制流分析"] 
        CFG --> RDA["可达定义分析(RDA)"]
        CFG --> VLA["活跃变量分析(VLA)"]
    
    end

    ClangAST --> |Interface| CommonUtils